## Welcome Hadi's first ever website. Its my first one so be kind.

I give most of the content credit to[Atlassian](https://www.atlassian.com/agile/scrum) and Also James Belchamber.

If you have come to learn about what Scrum is, why we use it and how it relates to Agile but is not the same thing... Then you've come to the right place.

### What is Scrum?

Scrum is a framework that helps teams work together. Much like a rugby team (where it gets its name) training for the big game, Scrum encourages teams to learn through experiences, self-organize while working on a problem, and reflect on their wins and losses to continuously improve.

While the Scrum I’m talking about is most frequently used by software development teams, its principles and lessons can be applied to all kinds of teamwork. This is one of the reasons Scrum is so popular. Often thought of as an agile project management framework, Scrum describes a set of meetings, tools, and roles that work in concert to help teams structure and manage their work.


# What are sprints? Im makng some changes to this

A sprint is a short, time-boxed period when a scrum team works to complete a set amount of work. Sprints are at the very heart of scrum and agile methodologies, and getting sprints right will help your agile team ship better software with fewer headaches.  

“With Scrum, a product is built in a series of iterations called sprints that break down big, complex projects into bite-sized pieces," said Megan Cook, Group Product Manager for Jira Software at Atlassian.

## The difference between Scrum and Agile?

Many people confuse Scrum and Agile as the same thing. They're not!
* Scrum is a framework for getting work done
* Agile is a set of values and principles
* A framewok like Scrum is there to help you start thinking in a more Agile way and to help you practice building Agile principles.